CREATE TABLE overview (
    symbol TEXT NOT NULL PRIMARY KEY,
    assetType TEXT,
    name TEXT,
    description TEXT,
    cIK TEXT,
    exchange TEXT,
    currency TEXT,
    country TEXT,
    sector TEXT,
    industry TEXT,
    address TEXT,
    officialSite TEXT,
    fiscalYearEnd TEXT,
    latestQuarter TEXT,
    marketCapitalization TEXT,
    eBITDA TEXT,
    pERatio TEXT,
    pEGRatio TEXT,
    bookValue TEXT,
    dividendPerShare TEXT,
    dividendYield TEXT,
    ePS TEXT,
    revenuePerShareTTM TEXT,
    profitMargin TEXT,
    operatingMarginTTM TEXT,
    returnOnAssetsTTM TEXT,
    returnOnEquityTTM TEXT,
    revenueTTM TEXT,
    grossProfitTTM TEXT,
    dilutedEPSTTM TEXT,
    quarterlyEarningsGrowthYOY TEXT,
    quarterlyRevenueGrowthYOY TEXT,
    analystTargetPrice TEXT,
    analystRatingStrongBuy TEXT,
    analystRatingBuy TEXT,
    analystRatingHold TEXT,
    analystRatingSell TEXT,
    analystRatingStrongSell TEXT,
    trailingPE TEXT,
    forwardPE TEXT,
    priceToSalesRatioTTM TEXT,
    priceToBookRatio TEXT,
    eVToRevenue TEXT,
    eVToEBITDA TEXT,
    beta TEXT,
    weekHigh52 TEXT,
    weekLow52 TEXT,
    dayMovingAverage50 TEXT,
    dayMovingAverage200 TEXT,
    sharesOutstanding TEXT,
    sharesFloat TEXT,
    percentInsiders TEXT,
    percentInstitutions TEXT,
    dividendDate TEXT,
    exDividendDate TEXT
);

CREATE TABLE income_statement (
    symbol TEXT NOT NULL,
    fiscalDateEnding TEXT NOT NULL,
    reportedCurrency TEXT,
    grossProfit TEXT,
    totalRevenue TEXT,
    costOfRevenue TEXT,
    costofGoodsAndServicesSold TEXT,
    operatingIncome TEXT,
    sellingGeneralAndAdministrative TEXT,
    researchAndDevelopment TEXT,
    operatingExpenses TEXT,
    investmentIncomeNet TEXT,
    netInterestIncome TEXT,
    interestIncome TEXT,
    interestExpense TEXT,
    nonInterestIncome TEXT,
    otherNonOperatingIncome TEXT,
    depreciation TEXT,
    depreciationAndAmortization TEXT,
    incomeBeforeTax TEXT,
    incomeTaxExpense TEXT,
    interestAndDebtExpense TEXT,
    netIncomeFromContinuingOperations TEXT,
    comprehensiveIncomeNetOfTax TEXT,
    ebit TEXT,
    ebitda TEXT,
    netIncome TEXT,

    FOREIGN KEY (symbol) REFERENCES overview(symbol) ON DELETE CASCADE,
    UNIQUE(symbol, fiscalDateEnding)
);

CREATE TABLE balance_sheet (
    symbol TEXT NOT NULL,
    fiscalDateEnding TEXT NOT NULL,
    reportedCurrency TEXT,
    totalAssets TEXT,
    totalCurrentAssets TEXT,
    cashAndCashEquivalentsAtCarryingValue TEXT,
    cashAndShortTermInvestments TEXT,
    inventory TEXT,
    currentNetReceivables TEXT,
    totalNonCurrentAssets TEXT,
    propertyPlantEquipment TEXT,
    accumulatedDepreciationAmortizationPPE TEXT,
    intangibleAssets TEXT,
    intangibleAssetsExcludingGoodwill TEXT,
    goodwill TEXT,
    investments TEXT,
    longTermInvestments TEXT,
    shortTermInvestments TEXT,
    otherCurrentAssets TEXT,
    otherNonCurrentAssets TEXT,
    totalLiabilities TEXT,
    totalCurrentLiabilities TEXT,
    currentAccountsPayable TEXT,
    deferredRevenue TEXT,
    currentDebt TEXT,
    shortTermDebt TEXT,
    totalNonCurrentLiabilities TEXT,
    capitalLeaseObligations TEXT,
    longTermDebt TEXT,
    currentLongTermDebt TEXT,
    longTermDebtNoncurrent TEXT,
    shortLongTermDebtTotal TEXT,
    otherCurrentLiabilities TEXT,
    otherNonCurrentLiabilities TEXT,
    totalShareholderEquity TEXT,
    treasuryStock TEXT,
    retainedEarnings TEXT,
    commonStock TEXT,
    commonStockSharesOutstanding TEXT,

    FOREIGN KEY (symbol) REFERENCES overview(symbol) ON DELETE CASCADE,
    UNIQUE(symbol, fiscalDateEnding)
);

CREATE TABLE cash_flow (
    symbol TEXT NOT NULL,
    fiscalDateEnding TEXT NOT NULL,
    reportedCurrency TEXT,
    operatingCashflow TEXT,
    paymentsForOperatingActivities TEXT,
    proceedsFromOperatingActivities TEXT,
    changeInOperatingLiabilities TEXT,
    changeInOperatingAssets TEXT,
    depreciationDepletionAndAmortization TEXT,
    capitalExpenditures TEXT,
    changeInReceivables TEXT,
    changeInInventory TEXT,
    profitLoss TEXT,
    cashflowFromInvestment TEXT,
    cashflowFromFinancing TEXT,
    proceedsFromRepaymentsOfShortTermDebt TEXT,
    paymentsForRepurchaseOfCommonStock TEXT,
    paymentsForRepurchaseOfEquity TEXT,
    paymentsForRepurchaseOfPreferredStock TEXT,
    dividendPayout TEXT,
    dividendPayoutCommonStock TEXT,
    dividendPayoutPreferredStock TEXT,
    proceedsFromIssuanceOfCommonStock TEXT,
    proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet TEXT,
    proceedsFromIssuanceOfPreferredStock TEXT,
    proceedsFromRepurchaseOfEquity TEXT,
    proceedsFromSaleOfTreasuryStock TEXT,
    stockBasedCompensation TEXT,
    changeInCashAndCashEquivalents TEXT,
    changeInExchangeRate TEXT,
    netIncome TEXT,

    FOREIGN KEY (symbol) REFERENCES overview(symbol) ON DELETE CASCADE,
    UNIQUE(symbol, fiscalDateEnding)
);