name: CI Pipeline

on:
  push:
    branches: "feature/vue-client"
  pull_request:
    branches: "main"

jobs:
  server-docker-build:
    uses: ./.github/workflows/build-and-push-docker.yml
    with:
      service-name: go-server
    secrets: inherit

  client-docker-build:
    uses: ./.github/workflows/build-and-push-docker.yml
    with:
      service-name: vue-client
    secrets: inherit

  db-docker-build:
    uses: ./.github/workflows/build-and-push-docker.yml
    with:
      service-name: postgres
    secrets: inherit

  # Публикация OCI-артефакта (после сборки всех образов)
  publish-oci:
    needs: [server-docker-build, client-docker-build, db-docker-build]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/publish-oci-artifact.yml
    secrets: inherit

  # Деплой на сервер (только для main ветки)
  deploy-to-acer-server:
    needs: publish-oci
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-to-server.yml
    with:
      environment: acer-server
    secrets: inherit