name: Publish OCI Artifact

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Publish OCI artifact
        run: |
            docker compose -f docker-compose.prod.yml publish --with-env -y \
            ghcr.io/${{ vars.REPO }}/tspo-app:${{ github.sha }}

            docker compose -f docker-compose.prod.yml publish --with-env -y \
            ghcr.io/${{ vars.REPO }}/tspo-app:latest